array_width = 100
attr_fn_like_width = 100
chain_width = 100
control_brace_style = "ClosingNextLine"
disable_all_formatting = false
edition = "2018"
fn_call_width = 100
fn_params_layout = "Tall"
force_explicit_abi = true
hard_tabs = true
match_arm_leading_pipes = "Preserve"
match_block_trailing_comma = true
max_width = 100
merge_derives = true
newline_style = "Unix"
remove_nested_parens = true
reorder_imports = true
reorder_modules = true
short_array_element_width_threshold = 10
single_line_if_else_max_width = 100
single_line_let_else_max_width = 100
struct_lit_width = 100
struct_variant_width = 100
tab_spaces = 4
use_field_init_shorthand = true
use_small_heuristics = "Max"
use_try_shorthand = true

binop_separator = "Front"
blank_lines_lower_bound = 0
blank_lines_upper_bound = 1
brace_style = "AlwaysNextLine"
combine_control_expr = true
comment_width = 80
condense_wildcard_suffixes = false
empty_item_single_line = true
enum_discrim_align_threshold = 20
error_on_line_overflow = false
error_on_unformatted = false
fn_single_line = true
force_multiline_blocks = false
format_code_in_doc_comments = false
doc_comment_code_block_width = 100
format_generated_files = false
format_macro_matchers = true
format_macro_bodies = true
format_strings = false
hex_literal_case = "Upper"
hide_parse_errors = false
imports_indent = "Block"
imports_layout = "HorizontalVertical"
indent_style = "Block"
inline_attribute_width = 0
match_arm_blocks = true
imports_granularity = "Crate"
normalize_comments = false
normalize_doc_attributes = true
overflow_delimited_expr = true
reorder_impl_items = true
group_imports = "StdExternalCrate"
required_version = "1.6.0"
skip_children = false
space_after_colon = true
space_before_colon = false
spaces_around_ranges = false
struct_field_align_threshold = 20
struct_lit_single_line = true
trailing_comma = "Vertical"
trailing_semicolon = true
type_punctuation_density = "Wide"
unstable_features = true
version = "Two"
where_single_line = false
wrap_comments = true

#color = "Auto"
#ignore = [...]
#skip_macro_invocations = []
