/* automatically generated by rust-bindgen 0.72.1 */

pub const NNG_MAJOR_VERSION: u32 = 2;
pub const NNG_MINOR_VERSION: u32 = 0;
pub const NNG_PATCH_VERSION: u32 = 0;
pub const NNG_RELEASE_SUFFIX: &[u8; 4] = b"dev\0";
pub const NNG_MAXADDRLEN: u32 = 128;
pub const NNG_DURATION_INFINITE: i32 = -1;
pub const NNG_DURATION_DEFAULT: i32 = -2;
pub const NNG_DURATION_ZERO: u32 = 0;
pub const NNG_MAXADDRSTRLEN: u32 = 144;
pub const NNG_FLAG_NONBLOCK: u32 = 2;
pub const NNG_OPT_RECVBUF: &[u8; 12] = b"recv-buffer\0";
pub const NNG_OPT_SENDBUF: &[u8; 12] = b"send-buffer\0";
pub const NNG_OPT_RECVTIMEO: &[u8; 13] = b"recv-timeout\0";
pub const NNG_OPT_SENDTIMEO: &[u8; 13] = b"send-timeout\0";
pub const NNG_OPT_LOCADDR: &[u8; 14] = b"local-address\0";
pub const NNG_OPT_REMADDR: &[u8; 15] = b"remote-address\0";
pub const NNG_OPT_MAXTTL: &[u8; 8] = b"ttl-max\0";
pub const NNG_OPT_RECVMAXSZ: &[u8; 14] = b"recv-size-max\0";
pub const NNG_OPT_RECONNMINT: &[u8; 19] = b"reconnect-time-min\0";
pub const NNG_OPT_RECONNMAXT: &[u8; 19] = b"reconnect-time-max\0";
pub const NNG_OPT_TLS_VERIFIED: &[u8; 13] = b"tls-verified\0";
pub const NNG_OPT_TLS_PEER_CN: &[u8; 12] = b"tls-peer-cn\0";
pub const NNG_OPT_TLS_PEER_ALT_NAMES: &[u8; 19] = b"tls-peer-alt-names\0";
pub const NNG_OPT_TCP_NODELAY: &[u8; 12] = b"tcp-nodelay\0";
pub const NNG_OPT_TCP_KEEPALIVE: &[u8; 14] = b"tcp-keepalive\0";
pub const NNG_OPT_TCP_BOUND_PORT: &[u8; 15] = b"tcp-bound-port\0";
pub const NNG_OPT_UDP_BOUND_PORT: &[u8; 15] = b"tcp-bound-port\0";
pub const NNG_OPT_UDP_COPY_MAX: &[u8; 13] = b"udp:copy-max\0";
pub const NNG_OPT_IPC_PERMISSIONS: &[u8; 16] = b"ipc:permissions\0";
pub const NNG_OPT_PEER_UID: &[u8; 13] = b"ipc:peer-uid\0";
pub const NNG_OPT_IPC_PEER_UID: &[u8; 13] = b"ipc:peer-uid\0";
pub const NNG_OPT_PEER_GID: &[u8; 13] = b"ipc:peer-gid\0";
pub const NNG_OPT_IPC_PEER_GID: &[u8; 13] = b"ipc:peer-gid\0";
pub const NNG_OPT_PEER_PID: &[u8; 13] = b"ipc:peer-pid\0";
pub const NNG_OPT_IPC_PEER_PID: &[u8; 13] = b"ipc:peer-pid\0";
pub const NNG_OPT_PEER_ZONEID: &[u8; 16] = b"ipc:peer-zoneid\0";
pub const NNG_OPT_IPC_PEER_ZONEID: &[u8; 16] = b"ipc:peer-zoneid\0";
pub const NNG_OPT_WS_HEADER: &[u8; 11] = b"ws:header:\0";
pub const NNG_OPT_WS_REQUEST_URI: &[u8; 15] = b"ws:request-uri\0";
pub const NNG_OPT_WS_SENDMAXFRAME: &[u8; 15] = b"ws:txframe-max\0";
pub const NNG_OPT_WS_RECVMAXFRAME: &[u8; 15] = b"ws:rxframe-max\0";
pub const NNG_OPT_WS_PROTOCOL: &[u8; 12] = b"ws:protocol\0";
pub const NNG_OPT_WS_SEND_TEXT: &[u8; 13] = b"ws:send-text\0";
pub const NNG_OPT_WS_RECV_TEXT: &[u8; 13] = b"ws:recv-text\0";
pub const NNG_OPT_SOCKET_FD: &[u8; 10] = b"socket:fd\0";
pub const NNG_OPT_LISTEN_FD: &[u8; 10] = b"listen-fd\0";
pub const NNG_MAP_RANDOM: u32 = 1;
pub const NNG_OPT_PAIR1_POLY: &[u8; 18] = b"pair1:polyamorous\0";
pub const NNG_OPT_SUB_PREFNEW: &[u8; 12] = b"sub:prefnew\0";
pub const NNG_OPT_REQ_RESENDTIME: &[u8; 16] = b"req:resend-time\0";
pub const NNG_OPT_REQ_RESENDTICK: &[u8; 16] = b"req:resend-tick\0";
pub const NNG_OPT_SURVEYOR_SURVEYTIME: &[u8; 21] = b"surveyor:survey-time\0";
pub const NNG_HTTP_VERSION_1_0: &[u8; 9] = b"HTTP/1.0\0";
pub const NNG_HTTP_VERSION_1_1: &[u8; 9] = b"HTTP/1.1\0";
pub const NNG_HTTP_VERSION_2: &[u8; 7] = b"HTTP/2\0";
pub const NNG_HTTP_VERSION_3: &[u8; 7] = b"HTTP/3\0";
#[repr(C)]
#[repr(align(4))]
#[derive(Debug, Default, Copy, Clone)]
pub struct nng_ctx_s {
    pub _bindgen_opaque_blob: u32,
}
pub type nng_ctx = nng_ctx_s;
#[repr(C)]
#[repr(align(4))]
#[derive(Debug, Default, Copy, Clone)]
pub struct nng_dialer_s {
    pub _bindgen_opaque_blob: u32,
}
pub type nng_dialer = nng_dialer_s;
#[repr(C)]
#[repr(align(4))]
#[derive(Debug, Default, Copy, Clone)]
pub struct nng_listener_s {
    pub _bindgen_opaque_blob: u32,
}
pub type nng_listener = nng_listener_s;
#[repr(C)]
#[repr(align(4))]
#[derive(Debug, Default, Copy, Clone)]
pub struct nng_pipe_s {
    pub _bindgen_opaque_blob: u32,
}
pub type nng_pipe = nng_pipe_s;
#[repr(C)]
#[repr(align(4))]
#[derive(Debug, Default, Copy, Clone)]
pub struct nng_socket_s {
    pub _bindgen_opaque_blob: u32,
}
pub type nng_socket = nng_socket_s;
pub type nng_duration = i32;
pub type nng_time = u64;
impl nng_err {
    pub const NNG_OK: nng_err = nng_err(0);
    pub const NNG_EINTR: nng_err = nng_err(1);
    pub const NNG_ENOMEM: nng_err = nng_err(2);
    pub const NNG_EINVAL: nng_err = nng_err(3);
    pub const NNG_EBUSY: nng_err = nng_err(4);
    pub const NNG_ETIMEDOUT: nng_err = nng_err(5);
    pub const NNG_ECONNREFUSED: nng_err = nng_err(6);
    pub const NNG_ECLOSED: nng_err = nng_err(7);
    pub const NNG_EAGAIN: nng_err = nng_err(8);
    pub const NNG_ENOTSUP: nng_err = nng_err(9);
    pub const NNG_EADDRINUSE: nng_err = nng_err(10);
    pub const NNG_ESTATE: nng_err = nng_err(11);
    pub const NNG_ENOENT: nng_err = nng_err(12);
    pub const NNG_EPROTO: nng_err = nng_err(13);
    pub const NNG_EUNREACHABLE: nng_err = nng_err(14);
    pub const NNG_EADDRINVAL: nng_err = nng_err(15);
    pub const NNG_EPERM: nng_err = nng_err(16);
    pub const NNG_EMSGSIZE: nng_err = nng_err(17);
    pub const NNG_ECONNABORTED: nng_err = nng_err(18);
    pub const NNG_ECONNRESET: nng_err = nng_err(19);
    pub const NNG_ECANCELED: nng_err = nng_err(20);
    pub const NNG_ENOFILES: nng_err = nng_err(21);
    pub const NNG_ENOSPC: nng_err = nng_err(22);
    pub const NNG_EEXIST: nng_err = nng_err(23);
    pub const NNG_EREADONLY: nng_err = nng_err(24);
    pub const NNG_EWRITEONLY: nng_err = nng_err(25);
    pub const NNG_ECRYPTO: nng_err = nng_err(26);
    pub const NNG_EPEERAUTH: nng_err = nng_err(27);
    pub const NNG_EBADTYPE: nng_err = nng_err(30);
    pub const NNG_ECONNSHUT: nng_err = nng_err(31);
    pub const NNG_ESTOPPED: nng_err = nng_err(999);
    pub const NNG_EINTERNAL: nng_err = nng_err(1000);
    pub const NNG_ESYSERR: nng_err = nng_err(268435456);
    pub const NNG_ETRANERR: nng_err = nng_err(536870912);
}
#[repr(transparent)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub struct nng_err(pub ::core::ffi::c_uint);
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct nng_msg {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct nng_stat {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct nng_aio {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct nng_url {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct nng_tls_config {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct nng_sockaddr_inproc {
    pub sa_family: u16,
    pub sa_name: [::core::ffi::c_char; 128usize],
}
impl Default for nng_sockaddr_inproc {
    fn default() -> Self {
        let mut s = ::core::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::core::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct nng_sockaddr_path {
    pub sa_family: u16,
    pub sa_path: [::core::ffi::c_char; 128usize],
}
impl Default for nng_sockaddr_path {
    fn default() -> Self {
        let mut s = ::core::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::core::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct nng_sockaddr_in6 {
    pub sa_family: u16,
    pub sa_port: u16,
    pub sa_scope: u32,
    pub sa_addr: [u8; 16usize],
}
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct nng_sockaddr_in {
    pub sa_family: u16,
    pub sa_port: u16,
    pub sa_addr: u32,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct nng_sockaddr_abstract {
    pub sa_family: u16,
    pub sa_len: u16,
    pub sa_name: [u8; 107usize],
}
impl Default for nng_sockaddr_abstract {
    fn default() -> Self {
        let mut s = ::core::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::core::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct nng_sockaddr_storage {
    pub sa_family: u16,
    pub sa_pad: [u64; 16usize],
}
pub type nng_sockaddr_ipc = nng_sockaddr_path;
#[repr(C)]
#[derive(Copy, Clone)]
pub union nng_sockaddr {
    pub s_family: u16,
    pub s_ipc: nng_sockaddr_ipc,
    pub s_inproc: nng_sockaddr_inproc,
    pub s_in6: nng_sockaddr_in6,
    pub s_in: nng_sockaddr_in,
    pub s_abstract: nng_sockaddr_abstract,
    pub s_storage: nng_sockaddr_storage,
}
impl Default for nng_sockaddr {
    fn default() -> Self {
        let mut s = ::core::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::core::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(u32)]
#[non_exhaustive]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum nng_sockaddr_family {
    NNG_AF_UNSPEC = 0,
    NNG_AF_INPROC = 1,
    NNG_AF_IPC = 2,
    NNG_AF_INET = 3,
    NNG_AF_INET6 = 4,
    NNG_AF_ABSTRACT = 5,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct nng_iov {
    pub iov_buf: *mut ::core::ffi::c_void,
    pub iov_len: usize,
}
impl Default for nng_iov {
    fn default() -> Self {
        let mut s = ::core::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::core::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
unsafe extern "C" {
    pub fn nng_socket_close(arg1: nng_socket) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn nng_socket_id(arg1: nng_socket) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn nng_socket_set_bool(
        arg1: nng_socket,
        arg2: *const ::core::ffi::c_char,
        arg3: bool,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn nng_socket_set_int(
        arg1: nng_socket,
        arg2: *const ::core::ffi::c_char,
        arg3: ::core::ffi::c_int,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn nng_socket_set_size(
        arg1: nng_socket,
        arg2: *const ::core::ffi::c_char,
        arg3: usize,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn nng_socket_set_ms(
        arg1: nng_socket,
        arg2: *const ::core::ffi::c_char,
        arg3: nng_duration,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn nng_socket_get_bool(
        arg1: nng_socket,
        arg2: *const ::core::ffi::c_char,
        arg3: *mut bool,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn nng_socket_get_int(
        arg1: nng_socket,
        arg2: *const ::core::ffi::c_char,
        arg3: *mut ::core::ffi::c_int,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn nng_socket_get_size(
        arg1: nng_socket,
        arg2: *const ::core::ffi::c_char,
        arg3: *mut usize,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn nng_socket_get_ms(
        arg1: nng_socket,
        arg2: *const ::core::ffi::c_char,
        arg3: *mut nng_duration,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn nng_socket_get_recv_poll_fd(
        id: nng_socket,
        fdp: *mut ::core::ffi::c_int,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn nng_socket_get_send_poll_fd(
        id: nng_socket,
        fdp: *mut ::core::ffi::c_int,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn nng_socket_proto_id(id: nng_socket, idp: *mut u16) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn nng_socket_peer_id(id: nng_socket, idp: *mut u16) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn nng_socket_proto_name(
        id: nng_socket,
        namep: *mut *const ::core::ffi::c_char,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn nng_socket_peer_name(
        id: nng_socket,
        namep: *mut *const ::core::ffi::c_char,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn nng_socket_raw(id: nng_socket, rawp: *mut bool) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn nng_str_sockaddr(
        sa: *const nng_sockaddr,
        buf: *mut ::core::ffi::c_char,
        bufsz: usize,
    ) -> *const ::core::ffi::c_char;
}
unsafe extern "C" {
    pub fn nng_sockaddr_port(sa: *const nng_sockaddr) -> u32;
}
unsafe extern "C" {
    pub fn nng_sockaddr_equal(sa1: *const nng_sockaddr, sa2: *const nng_sockaddr) -> bool;
}
unsafe extern "C" {
    pub fn nng_sockaddr_hash(sa: *const nng_sockaddr) -> u64;
}
pub const NNG_PIPE_EV_NONE: nng_pipe_ev = 0;
pub const NNG_PIPE_EV_ADD_PRE: nng_pipe_ev = 1;
pub const NNG_PIPE_EV_ADD_POST: nng_pipe_ev = 2;
pub const NNG_PIPE_EV_REM_POST: nng_pipe_ev = 3;
pub type nng_pipe_ev = ::core::ffi::c_uint;
pub type nng_pipe_cb = ::core::option::Option<
    unsafe extern "C" fn(arg1: nng_pipe, arg2: nng_pipe_ev, arg3: *mut ::core::ffi::c_void),
>;
unsafe extern "C" {
    pub fn nng_pipe_notify(
        arg1: nng_socket,
        arg2: nng_pipe_ev,
        arg3: nng_pipe_cb,
        arg4: *mut ::core::ffi::c_void,
    ) -> nng_err;
}
unsafe extern "C" {
    pub fn nng_listen(
        arg1: nng_socket,
        arg2: *const ::core::ffi::c_char,
        arg3: *mut nng_listener,
        arg4: ::core::ffi::c_int,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn nng_listen_url(
        arg1: nng_socket,
        arg2: *const nng_url,
        arg3: *mut nng_listener,
        arg4: ::core::ffi::c_int,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn nng_dial(
        arg1: nng_socket,
        arg2: *const ::core::ffi::c_char,
        arg3: *mut nng_dialer,
        arg4: ::core::ffi::c_int,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn nng_dial_url(
        arg1: nng_socket,
        url: *const nng_url,
        arg2: *mut nng_dialer,
        arg3: ::core::ffi::c_int,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn nng_dialer_create(
        arg1: *mut nng_dialer,
        arg2: nng_socket,
        arg3: *const ::core::ffi::c_char,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn nng_dialer_create_url(
        arg1: *mut nng_dialer,
        arg2: nng_socket,
        arg3: *const nng_url,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn nng_listener_create(
        arg1: *mut nng_listener,
        arg2: nng_socket,
        arg3: *const ::core::ffi::c_char,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn nng_listener_create_url(
        arg1: *mut nng_listener,
        arg2: nng_socket,
        arg3: *const nng_url,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn nng_dialer_start(arg1: nng_dialer, arg2: ::core::ffi::c_int) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn nng_dialer_start_aio(arg1: nng_dialer, arg2: ::core::ffi::c_int, arg3: *mut nng_aio);
}
unsafe extern "C" {
    pub fn nng_listener_start(arg1: nng_listener, arg2: ::core::ffi::c_int) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn nng_dialer_close(arg1: nng_dialer) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn nng_listener_close(arg1: nng_listener) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn nng_dialer_id(arg1: nng_dialer) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn nng_listener_id(arg1: nng_listener) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn nng_dialer_set_bool(
        arg1: nng_dialer,
        arg2: *const ::core::ffi::c_char,
        arg3: bool,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn nng_dialer_set_int(
        arg1: nng_dialer,
        arg2: *const ::core::ffi::c_char,
        arg3: ::core::ffi::c_int,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn nng_dialer_set_size(
        arg1: nng_dialer,
        arg2: *const ::core::ffi::c_char,
        arg3: usize,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn nng_dialer_set_uint64(
        arg1: nng_dialer,
        arg2: *const ::core::ffi::c_char,
        arg3: u64,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn nng_dialer_set_string(
        arg1: nng_dialer,
        arg2: *const ::core::ffi::c_char,
        arg3: *const ::core::ffi::c_char,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn nng_dialer_set_ms(
        arg1: nng_dialer,
        arg2: *const ::core::ffi::c_char,
        arg3: nng_duration,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn nng_dialer_set_addr(
        arg1: nng_dialer,
        arg2: *const ::core::ffi::c_char,
        arg3: *const nng_sockaddr,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn nng_dialer_set_tls(arg1: nng_dialer, arg2: *mut nng_tls_config) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn nng_dialer_get_bool(
        arg1: nng_dialer,
        arg2: *const ::core::ffi::c_char,
        arg3: *mut bool,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn nng_dialer_get_int(
        arg1: nng_dialer,
        arg2: *const ::core::ffi::c_char,
        arg3: *mut ::core::ffi::c_int,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn nng_dialer_get_size(
        arg1: nng_dialer,
        arg2: *const ::core::ffi::c_char,
        arg3: *mut usize,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn nng_dialer_get_uint64(
        arg1: nng_dialer,
        arg2: *const ::core::ffi::c_char,
        arg3: *mut u64,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn nng_dialer_get_string(
        arg1: nng_dialer,
        arg2: *const ::core::ffi::c_char,
        arg3: *mut *mut ::core::ffi::c_char,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn nng_dialer_get_ms(
        arg1: nng_dialer,
        arg2: *const ::core::ffi::c_char,
        arg3: *mut nng_duration,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn nng_dialer_get_addr(
        arg1: nng_dialer,
        arg2: *const ::core::ffi::c_char,
        arg3: *mut nng_sockaddr,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn nng_dialer_get_tls(
        arg1: nng_dialer,
        arg2: *mut *mut nng_tls_config,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn nng_dialer_get_url(id: nng_dialer, urlp: *mut *const nng_url) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn nng_listener_set_bool(
        arg1: nng_listener,
        arg2: *const ::core::ffi::c_char,
        arg3: bool,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn nng_listener_set_int(
        arg1: nng_listener,
        arg2: *const ::core::ffi::c_char,
        arg3: ::core::ffi::c_int,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn nng_listener_set_size(
        arg1: nng_listener,
        arg2: *const ::core::ffi::c_char,
        arg3: usize,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn nng_listener_set_uint64(
        arg1: nng_listener,
        arg2: *const ::core::ffi::c_char,
        arg3: u64,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn nng_listener_set_string(
        arg1: nng_listener,
        arg2: *const ::core::ffi::c_char,
        arg3: *const ::core::ffi::c_char,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn nng_listener_set_ms(
        arg1: nng_listener,
        arg2: *const ::core::ffi::c_char,
        arg3: nng_duration,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn nng_listener_set_addr(
        arg1: nng_listener,
        arg2: *const ::core::ffi::c_char,
        arg3: *const nng_sockaddr,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn nng_listener_set_tls(
        arg1: nng_listener,
        arg2: *mut nng_tls_config,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn nng_listener_set_security_descriptor(
        arg1: nng_listener,
        arg2: *mut ::core::ffi::c_void,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn nng_listener_get_url(id: nng_listener, urlp: *mut *const nng_url) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn nng_listener_get_bool(
        arg1: nng_listener,
        arg2: *const ::core::ffi::c_char,
        arg3: *mut bool,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn nng_listener_get_int(
        arg1: nng_listener,
        arg2: *const ::core::ffi::c_char,
        arg3: *mut ::core::ffi::c_int,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn nng_listener_get_size(
        arg1: nng_listener,
        arg2: *const ::core::ffi::c_char,
        arg3: *mut usize,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn nng_listener_get_uint64(
        arg1: nng_listener,
        arg2: *const ::core::ffi::c_char,
        arg3: *mut u64,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn nng_listener_get_string(
        arg1: nng_listener,
        arg2: *const ::core::ffi::c_char,
        arg3: *mut *mut ::core::ffi::c_char,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn nng_listener_get_ms(
        arg1: nng_listener,
        arg2: *const ::core::ffi::c_char,
        arg3: *mut nng_duration,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn nng_listener_get_addr(
        arg1: nng_listener,
        arg2: *const ::core::ffi::c_char,
        arg3: *mut nng_sockaddr,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn nng_listener_get_tls(
        arg1: nng_listener,
        arg2: *mut *mut nng_tls_config,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn nng_strerror(arg1: nng_err) -> *const ::core::ffi::c_char;
}
unsafe extern "C" {
    pub fn nng_send(
        arg1: nng_socket,
        arg2: *const ::core::ffi::c_void,
        arg3: usize,
        arg4: ::core::ffi::c_int,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn nng_recv(
        arg1: nng_socket,
        arg2: *mut ::core::ffi::c_void,
        arg3: *mut usize,
        arg4: ::core::ffi::c_int,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn nng_sendmsg(
        arg1: nng_socket,
        arg2: *mut nng_msg,
        arg3: ::core::ffi::c_int,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn nng_recvmsg(
        arg1: nng_socket,
        arg2: *mut *mut nng_msg,
        arg3: ::core::ffi::c_int,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn nng_socket_send(arg1: nng_socket, arg2: *mut nng_aio);
}
unsafe extern "C" {
    pub fn nng_socket_recv(arg1: nng_socket, arg2: *mut nng_aio);
}
unsafe extern "C" {
    pub fn nng_ctx_open(arg1: *mut nng_ctx, arg2: nng_socket) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn nng_ctx_close(arg1: nng_ctx) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn nng_ctx_id(arg1: nng_ctx) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn nng_ctx_recv(arg1: nng_ctx, arg2: *mut nng_aio);
}
unsafe extern "C" {
    pub fn nng_ctx_recvmsg(
        arg1: nng_ctx,
        arg2: *mut *mut nng_msg,
        arg3: ::core::ffi::c_int,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn nng_ctx_send(arg1: nng_ctx, arg2: *mut nng_aio);
}
unsafe extern "C" {
    pub fn nng_ctx_sendmsg(
        arg1: nng_ctx,
        arg2: *mut nng_msg,
        arg3: ::core::ffi::c_int,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn nng_ctx_get_bool(
        arg1: nng_ctx,
        arg2: *const ::core::ffi::c_char,
        arg3: *mut bool,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn nng_ctx_get_int(
        arg1: nng_ctx,
        arg2: *const ::core::ffi::c_char,
        arg3: *mut ::core::ffi::c_int,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn nng_ctx_get_size(
        arg1: nng_ctx,
        arg2: *const ::core::ffi::c_char,
        arg3: *mut usize,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn nng_ctx_get_ms(
        arg1: nng_ctx,
        arg2: *const ::core::ffi::c_char,
        arg3: *mut nng_duration,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn nng_ctx_set(
        arg1: nng_ctx,
        arg2: *const ::core::ffi::c_char,
        arg3: *const ::core::ffi::c_void,
        arg4: usize,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn nng_ctx_set_bool(
        arg1: nng_ctx,
        arg2: *const ::core::ffi::c_char,
        arg3: bool,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn nng_ctx_set_int(
        arg1: nng_ctx,
        arg2: *const ::core::ffi::c_char,
        arg3: ::core::ffi::c_int,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn nng_ctx_set_size(
        arg1: nng_ctx,
        arg2: *const ::core::ffi::c_char,
        arg3: usize,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn nng_ctx_set_ms(
        arg1: nng_ctx,
        arg2: *const ::core::ffi::c_char,
        arg3: nng_duration,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn nng_alloc(arg1: usize) -> *mut ::core::ffi::c_void;
}
unsafe extern "C" {
    pub fn nng_free(arg1: *mut ::core::ffi::c_void, arg2: usize);
}
unsafe extern "C" {
    pub fn nng_strdup(arg1: *const ::core::ffi::c_char) -> *mut ::core::ffi::c_char;
}
unsafe extern "C" {
    pub fn nng_strfree(arg1: *mut ::core::ffi::c_char);
}
unsafe extern "C" {
    pub fn nng_aio_alloc(
        arg1: *mut *mut nng_aio,
        arg2: ::core::option::Option<unsafe extern "C" fn(arg1: *mut ::core::ffi::c_void)>,
        arg3: *mut ::core::ffi::c_void,
    ) -> nng_err;
}
unsafe extern "C" {
    pub fn nng_aio_free(arg1: *mut nng_aio);
}
unsafe extern "C" {
    pub fn nng_aio_reap(arg1: *mut nng_aio);
}
unsafe extern "C" {
    pub fn nng_aio_stop(arg1: *mut nng_aio);
}
unsafe extern "C" {
    pub fn nng_aio_result(arg1: *mut nng_aio) -> nng_err;
}
unsafe extern "C" {
    pub fn nng_aio_count(arg1: *mut nng_aio) -> usize;
}
unsafe extern "C" {
    pub fn nng_aio_cancel(arg1: *mut nng_aio);
}
unsafe extern "C" {
    pub fn nng_aio_abort(arg1: *mut nng_aio, arg2: nng_err);
}
unsafe extern "C" {
    pub fn nng_aio_wait(arg1: *mut nng_aio);
}
unsafe extern "C" {
    pub fn nng_aio_busy(arg1: *mut nng_aio) -> bool;
}
unsafe extern "C" {
    pub fn nng_aio_set_msg(arg1: *mut nng_aio, arg2: *mut nng_msg);
}
unsafe extern "C" {
    pub fn nng_aio_get_msg(arg1: *mut nng_aio) -> *mut nng_msg;
}
unsafe extern "C" {
    pub fn nng_aio_set_input(
        arg1: *mut nng_aio,
        arg2: ::core::ffi::c_uint,
        arg3: *mut ::core::ffi::c_void,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn nng_aio_get_input(
        arg1: *mut nng_aio,
        arg2: ::core::ffi::c_uint,
    ) -> *mut ::core::ffi::c_void;
}
unsafe extern "C" {
    pub fn nng_aio_set_output(
        arg1: *mut nng_aio,
        arg2: ::core::ffi::c_uint,
        arg3: *mut ::core::ffi::c_void,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn nng_aio_get_output(
        arg1: *mut nng_aio,
        arg2: ::core::ffi::c_uint,
    ) -> *mut ::core::ffi::c_void;
}
unsafe extern "C" {
    pub fn nng_aio_set_timeout(arg1: *mut nng_aio, arg2: nng_duration);
}
unsafe extern "C" {
    pub fn nng_aio_set_expire(arg1: *mut nng_aio, arg2: nng_time);
}
unsafe extern "C" {
    pub fn nng_aio_set_iov(
        arg1: *mut nng_aio,
        arg2: ::core::ffi::c_uint,
        arg3: *const nng_iov,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn nng_aio_reset(arg1: *mut nng_aio);
}
unsafe extern "C" {
    pub fn nng_aio_finish(arg1: *mut nng_aio, arg2: ::core::ffi::c_int);
}
pub type nng_aio_cancelfn = ::core::option::Option<
    unsafe extern "C" fn(arg1: *mut nng_aio, arg2: *mut ::core::ffi::c_void, arg3: nng_err),
>;
unsafe extern "C" {
    pub fn nng_aio_start(
        arg1: *mut nng_aio,
        arg2: nng_aio_cancelfn,
        arg3: *mut ::core::ffi::c_void,
    ) -> bool;
}
unsafe extern "C" {
    pub fn nng_sleep_aio(arg1: nng_duration, arg2: *mut nng_aio);
}
unsafe extern "C" {
    pub fn nng_msg_alloc(arg1: *mut *mut nng_msg, arg2: usize) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn nng_msg_free(arg1: *mut nng_msg);
}
unsafe extern "C" {
    pub fn nng_msg_realloc(arg1: *mut nng_msg, arg2: usize) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn nng_msg_reserve(arg1: *mut nng_msg, arg2: usize) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn nng_msg_capacity(arg1: *mut nng_msg) -> usize;
}
unsafe extern "C" {
    pub fn nng_msg_header(arg1: *mut nng_msg) -> *mut ::core::ffi::c_void;
}
unsafe extern "C" {
    pub fn nng_msg_header_len(arg1: *const nng_msg) -> usize;
}
unsafe extern "C" {
    pub fn nng_msg_body(arg1: *mut nng_msg) -> *mut ::core::ffi::c_void;
}
unsafe extern "C" {
    pub fn nng_msg_len(arg1: *const nng_msg) -> usize;
}
unsafe extern "C" {
    pub fn nng_msg_append(
        arg1: *mut nng_msg,
        arg2: *const ::core::ffi::c_void,
        arg3: usize,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn nng_msg_insert(
        arg1: *mut nng_msg,
        arg2: *const ::core::ffi::c_void,
        arg3: usize,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn nng_msg_trim(arg1: *mut nng_msg, arg2: usize) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn nng_msg_chop(arg1: *mut nng_msg, arg2: usize) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn nng_msg_header_append(
        arg1: *mut nng_msg,
        arg2: *const ::core::ffi::c_void,
        arg3: usize,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn nng_msg_header_insert(
        arg1: *mut nng_msg,
        arg2: *const ::core::ffi::c_void,
        arg3: usize,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn nng_msg_header_trim(arg1: *mut nng_msg, arg2: usize) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn nng_msg_header_chop(arg1: *mut nng_msg, arg2: usize) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn nng_msg_header_append_u16(arg1: *mut nng_msg, arg2: u16) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn nng_msg_header_append_u32(arg1: *mut nng_msg, arg2: u32) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn nng_msg_header_append_u64(arg1: *mut nng_msg, arg2: u64) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn nng_msg_header_insert_u16(arg1: *mut nng_msg, arg2: u16) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn nng_msg_header_insert_u32(arg1: *mut nng_msg, arg2: u32) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn nng_msg_header_insert_u64(arg1: *mut nng_msg, arg2: u64) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn nng_msg_header_chop_u16(arg1: *mut nng_msg, arg2: *mut u16) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn nng_msg_header_chop_u32(arg1: *mut nng_msg, arg2: *mut u32) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn nng_msg_header_chop_u64(arg1: *mut nng_msg, arg2: *mut u64) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn nng_msg_header_trim_u16(arg1: *mut nng_msg, arg2: *mut u16) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn nng_msg_header_trim_u32(arg1: *mut nng_msg, arg2: *mut u32) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn nng_msg_header_trim_u64(arg1: *mut nng_msg, arg2: *mut u64) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn nng_msg_append_u16(arg1: *mut nng_msg, arg2: u16) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn nng_msg_append_u32(arg1: *mut nng_msg, arg2: u32) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn nng_msg_append_u64(arg1: *mut nng_msg, arg2: u64) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn nng_msg_insert_u16(arg1: *mut nng_msg, arg2: u16) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn nng_msg_insert_u32(arg1: *mut nng_msg, arg2: u32) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn nng_msg_insert_u64(arg1: *mut nng_msg, arg2: u64) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn nng_msg_chop_u16(arg1: *mut nng_msg, arg2: *mut u16) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn nng_msg_chop_u32(arg1: *mut nng_msg, arg2: *mut u32) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn nng_msg_chop_u64(arg1: *mut nng_msg, arg2: *mut u64) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn nng_msg_trim_u16(arg1: *mut nng_msg, arg2: *mut u16) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn nng_msg_trim_u32(arg1: *mut nng_msg, arg2: *mut u32) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn nng_msg_trim_u64(arg1: *mut nng_msg, arg2: *mut u64) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn nng_msg_dup(arg1: *mut *mut nng_msg, arg2: *const nng_msg) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn nng_msg_clear(arg1: *mut nng_msg);
}
unsafe extern "C" {
    pub fn nng_msg_header_clear(arg1: *mut nng_msg);
}
unsafe extern "C" {
    pub fn nng_msg_set_pipe(arg1: *mut nng_msg, arg2: nng_pipe);
}
unsafe extern "C" {
    pub fn nng_msg_get_pipe(arg1: *const nng_msg) -> nng_pipe;
}
unsafe extern "C" {
    pub fn nng_pipe_get_bool(
        arg1: nng_pipe,
        arg2: *const ::core::ffi::c_char,
        arg3: *mut bool,
    ) -> nng_err;
}
unsafe extern "C" {
    pub fn nng_pipe_get_int(
        arg1: nng_pipe,
        arg2: *const ::core::ffi::c_char,
        arg3: *mut ::core::ffi::c_int,
    ) -> nng_err;
}
unsafe extern "C" {
    pub fn nng_pipe_get_ms(
        arg1: nng_pipe,
        arg2: *const ::core::ffi::c_char,
        arg3: *mut nng_duration,
    ) -> nng_err;
}
unsafe extern "C" {
    pub fn nng_pipe_get_size(
        arg1: nng_pipe,
        arg2: *const ::core::ffi::c_char,
        arg3: *mut usize,
    ) -> nng_err;
}
unsafe extern "C" {
    pub fn nng_pipe_get_string(
        arg1: nng_pipe,
        arg2: *const ::core::ffi::c_char,
        arg3: *mut *mut ::core::ffi::c_char,
    ) -> nng_err;
}
unsafe extern "C" {
    pub fn nng_pipe_get_addr(
        arg1: nng_pipe,
        arg2: *const ::core::ffi::c_char,
        arg3: *mut nng_sockaddr,
    ) -> nng_err;
}
unsafe extern "C" {
    pub fn nng_pipe_close(arg1: nng_pipe) -> nng_err;
}
unsafe extern "C" {
    pub fn nng_pipe_id(arg1: nng_pipe) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn nng_pipe_socket(arg1: nng_pipe) -> nng_socket;
}
unsafe extern "C" {
    pub fn nng_pipe_dialer(arg1: nng_pipe) -> nng_dialer;
}
unsafe extern "C" {
    pub fn nng_pipe_listener(arg1: nng_pipe) -> nng_listener;
}
unsafe extern "C" {
    pub fn nng_stats_get(arg1: *mut *mut nng_stat) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn nng_stats_free(arg1: *mut nng_stat);
}
unsafe extern "C" {
    pub fn nng_stats_dump(arg1: *const nng_stat);
}
unsafe extern "C" {
    pub fn nng_stat_next(arg1: *const nng_stat) -> *const nng_stat;
}
unsafe extern "C" {
    pub fn nng_stat_child(arg1: *const nng_stat) -> *const nng_stat;
}
unsafe extern "C" {
    pub fn nng_stat_name(arg1: *const nng_stat) -> *const ::core::ffi::c_char;
}
unsafe extern "C" {
    pub fn nng_stat_type(arg1: *const nng_stat) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn nng_stat_find(
        arg1: *const nng_stat,
        arg2: *const ::core::ffi::c_char,
    ) -> *const nng_stat;
}
unsafe extern "C" {
    pub fn nng_stat_find_socket(arg1: *const nng_stat, arg2: nng_socket) -> *const nng_stat;
}
unsafe extern "C" {
    pub fn nng_stat_find_dialer(arg1: *const nng_stat, arg2: nng_dialer) -> *const nng_stat;
}
unsafe extern "C" {
    pub fn nng_stat_find_listener(arg1: *const nng_stat, arg2: nng_listener) -> *const nng_stat;
}
#[repr(u32)]
#[non_exhaustive]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum nng_stat_type_enum {
    NNG_STAT_SCOPE = 0,
    NNG_STAT_LEVEL = 1,
    NNG_STAT_COUNTER = 2,
    NNG_STAT_STRING = 3,
    NNG_STAT_BOOLEAN = 4,
    NNG_STAT_ID = 5,
}
unsafe extern "C" {
    pub fn nng_stat_unit(arg1: *const nng_stat) -> ::core::ffi::c_int;
}
#[repr(u32)]
#[non_exhaustive]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum nng_unit_enum {
    NNG_UNIT_NONE = 0,
    NNG_UNIT_BYTES = 1,
    NNG_UNIT_MESSAGES = 2,
    NNG_UNIT_MILLIS = 3,
    NNG_UNIT_EVENTS = 4,
}
unsafe extern "C" {
    pub fn nng_stat_value(arg1: *const nng_stat) -> u64;
}
unsafe extern "C" {
    pub fn nng_stat_bool(arg1: *const nng_stat) -> bool;
}
unsafe extern "C" {
    pub fn nng_stat_string(arg1: *const nng_stat) -> *const ::core::ffi::c_char;
}
unsafe extern "C" {
    pub fn nng_stat_desc(arg1: *const nng_stat) -> *const ::core::ffi::c_char;
}
unsafe extern "C" {
    pub fn nng_stat_timestamp(arg1: *const nng_stat) -> u64;
}
unsafe extern "C" {
    pub fn nng_device(arg1: nng_socket, arg2: nng_socket) -> nng_err;
}
unsafe extern "C" {
    pub fn nng_device_aio(arg1: *mut nng_aio, arg2: nng_socket, arg3: nng_socket);
}
unsafe extern "C" {
    pub fn nng_url_parse(arg1: *mut *mut nng_url, arg2: *const ::core::ffi::c_char) -> nng_err;
}
unsafe extern "C" {
    pub fn nng_url_free(arg1: *mut nng_url);
}
unsafe extern "C" {
    pub fn nng_url_clone(arg1: *mut *mut nng_url, arg2: *const nng_url) -> nng_err;
}
unsafe extern "C" {
    pub fn nng_url_sprintf(
        arg1: *mut ::core::ffi::c_char,
        arg2: usize,
        arg3: *const nng_url,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn nng_url_scheme(arg1: *const nng_url) -> *const ::core::ffi::c_char;
}
unsafe extern "C" {
    pub fn nng_url_port(arg1: *const nng_url) -> u32;
}
unsafe extern "C" {
    pub fn nng_url_resolve_port(url: *mut nng_url, port: u32);
}
unsafe extern "C" {
    pub fn nng_url_hostname(arg1: *const nng_url) -> *const ::core::ffi::c_char;
}
unsafe extern "C" {
    pub fn nng_url_userinfo(arg1: *const nng_url) -> *const ::core::ffi::c_char;
}
unsafe extern "C" {
    pub fn nng_url_path(arg1: *const nng_url) -> *const ::core::ffi::c_char;
}
unsafe extern "C" {
    pub fn nng_url_query(arg1: *const nng_url) -> *const ::core::ffi::c_char;
}
unsafe extern "C" {
    pub fn nng_url_fragment(arg1: *const nng_url) -> *const ::core::ffi::c_char;
}
unsafe extern "C" {
    pub fn nng_version() -> *const ::core::ffi::c_char;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct nng_stream {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct nng_stream_dialer {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct nng_stream_listener {
    _unused: [u8; 0],
}
unsafe extern "C" {
    pub fn nng_stream_free(arg1: *mut nng_stream);
}
unsafe extern "C" {
    pub fn nng_stream_close(arg1: *mut nng_stream);
}
unsafe extern "C" {
    pub fn nng_stream_stop(arg1: *mut nng_stream);
}
unsafe extern "C" {
    pub fn nng_stream_send(arg1: *mut nng_stream, arg2: *mut nng_aio);
}
unsafe extern "C" {
    pub fn nng_stream_recv(arg1: *mut nng_stream, arg2: *mut nng_aio);
}
unsafe extern "C" {
    pub fn nng_stream_get_bool(
        arg1: *mut nng_stream,
        arg2: *const ::core::ffi::c_char,
        arg3: *mut bool,
    ) -> nng_err;
}
unsafe extern "C" {
    pub fn nng_stream_get_int(
        arg1: *mut nng_stream,
        arg2: *const ::core::ffi::c_char,
        arg3: *mut ::core::ffi::c_int,
    ) -> nng_err;
}
unsafe extern "C" {
    pub fn nng_stream_get_ms(
        arg1: *mut nng_stream,
        arg2: *const ::core::ffi::c_char,
        arg3: *mut nng_duration,
    ) -> nng_err;
}
unsafe extern "C" {
    pub fn nng_stream_get_size(
        arg1: *mut nng_stream,
        arg2: *const ::core::ffi::c_char,
        arg3: *mut usize,
    ) -> nng_err;
}
unsafe extern "C" {
    pub fn nng_stream_get_uint64(
        arg1: *mut nng_stream,
        arg2: *const ::core::ffi::c_char,
        arg3: *mut u64,
    ) -> nng_err;
}
unsafe extern "C" {
    pub fn nng_stream_get_string(
        arg1: *mut nng_stream,
        arg2: *const ::core::ffi::c_char,
        arg3: *mut *mut ::core::ffi::c_char,
    ) -> nng_err;
}
unsafe extern "C" {
    pub fn nng_stream_get_addr(
        arg1: *mut nng_stream,
        arg2: *const ::core::ffi::c_char,
        arg3: *mut nng_sockaddr,
    ) -> nng_err;
}
unsafe extern "C" {
    pub fn nng_stream_dialer_alloc(
        arg1: *mut *mut nng_stream_dialer,
        arg2: *const ::core::ffi::c_char,
    ) -> nng_err;
}
unsafe extern "C" {
    pub fn nng_stream_dialer_alloc_url(
        arg1: *mut *mut nng_stream_dialer,
        arg2: *const nng_url,
    ) -> nng_err;
}
unsafe extern "C" {
    pub fn nng_stream_dialer_free(arg1: *mut nng_stream_dialer);
}
unsafe extern "C" {
    pub fn nng_stream_dialer_close(arg1: *mut nng_stream_dialer);
}
unsafe extern "C" {
    pub fn nng_stream_dialer_stop(arg1: *mut nng_stream_dialer);
}
unsafe extern "C" {
    pub fn nng_stream_dialer_dial(arg1: *mut nng_stream_dialer, arg2: *mut nng_aio);
}
unsafe extern "C" {
    pub fn nng_stream_dialer_get_bool(
        arg1: *mut nng_stream_dialer,
        arg2: *const ::core::ffi::c_char,
        arg3: *mut bool,
    ) -> nng_err;
}
unsafe extern "C" {
    pub fn nng_stream_dialer_get_int(
        arg1: *mut nng_stream_dialer,
        arg2: *const ::core::ffi::c_char,
        arg3: *mut ::core::ffi::c_int,
    ) -> nng_err;
}
unsafe extern "C" {
    pub fn nng_stream_dialer_get_ms(
        arg1: *mut nng_stream_dialer,
        arg2: *const ::core::ffi::c_char,
        arg3: *mut nng_duration,
    ) -> nng_err;
}
unsafe extern "C" {
    pub fn nng_stream_dialer_get_size(
        arg1: *mut nng_stream_dialer,
        arg2: *const ::core::ffi::c_char,
        arg3: *mut usize,
    ) -> nng_err;
}
unsafe extern "C" {
    pub fn nng_stream_dialer_get_uint64(
        arg1: *mut nng_stream_dialer,
        arg2: *const ::core::ffi::c_char,
        arg3: *mut u64,
    ) -> nng_err;
}
unsafe extern "C" {
    pub fn nng_stream_dialer_get_string(
        arg1: *mut nng_stream_dialer,
        arg2: *const ::core::ffi::c_char,
        arg3: *mut *mut ::core::ffi::c_char,
    ) -> nng_err;
}
unsafe extern "C" {
    pub fn nng_stream_dialer_get_addr(
        arg1: *mut nng_stream_dialer,
        arg2: *const ::core::ffi::c_char,
        arg3: *mut nng_sockaddr,
    ) -> nng_err;
}
unsafe extern "C" {
    pub fn nng_stream_dialer_set_bool(
        arg1: *mut nng_stream_dialer,
        arg2: *const ::core::ffi::c_char,
        arg3: bool,
    ) -> nng_err;
}
unsafe extern "C" {
    pub fn nng_stream_dialer_set_int(
        arg1: *mut nng_stream_dialer,
        arg2: *const ::core::ffi::c_char,
        arg3: ::core::ffi::c_int,
    ) -> nng_err;
}
unsafe extern "C" {
    pub fn nng_stream_dialer_set_ms(
        arg1: *mut nng_stream_dialer,
        arg2: *const ::core::ffi::c_char,
        arg3: nng_duration,
    ) -> nng_err;
}
unsafe extern "C" {
    pub fn nng_stream_dialer_set_size(
        arg1: *mut nng_stream_dialer,
        arg2: *const ::core::ffi::c_char,
        arg3: usize,
    ) -> nng_err;
}
unsafe extern "C" {
    pub fn nng_stream_dialer_set_uint64(
        arg1: *mut nng_stream_dialer,
        arg2: *const ::core::ffi::c_char,
        arg3: u64,
    ) -> nng_err;
}
unsafe extern "C" {
    pub fn nng_stream_dialer_set_string(
        arg1: *mut nng_stream_dialer,
        arg2: *const ::core::ffi::c_char,
        arg3: *const ::core::ffi::c_char,
    ) -> nng_err;
}
unsafe extern "C" {
    pub fn nng_stream_dialer_set_addr(
        arg1: *mut nng_stream_dialer,
        arg2: *const ::core::ffi::c_char,
        arg3: *const nng_sockaddr,
    ) -> nng_err;
}
unsafe extern "C" {
    pub fn nng_stream_dialer_get_tls(
        arg1: *mut nng_stream_dialer,
        arg2: *mut *mut nng_tls_config,
    ) -> nng_err;
}
unsafe extern "C" {
    pub fn nng_stream_dialer_set_tls(
        arg1: *mut nng_stream_dialer,
        arg2: *mut nng_tls_config,
    ) -> nng_err;
}
unsafe extern "C" {
    pub fn nng_stream_listener_alloc(
        arg1: *mut *mut nng_stream_listener,
        arg2: *const ::core::ffi::c_char,
    ) -> nng_err;
}
unsafe extern "C" {
    pub fn nng_stream_listener_alloc_url(
        arg1: *mut *mut nng_stream_listener,
        arg2: *const nng_url,
    ) -> nng_err;
}
unsafe extern "C" {
    pub fn nng_stream_listener_free(arg1: *mut nng_stream_listener);
}
unsafe extern "C" {
    pub fn nng_stream_listener_close(arg1: *mut nng_stream_listener);
}
unsafe extern "C" {
    pub fn nng_stream_listener_stop(arg1: *mut nng_stream_listener);
}
unsafe extern "C" {
    pub fn nng_stream_listener_listen(arg1: *mut nng_stream_listener) -> nng_err;
}
unsafe extern "C" {
    pub fn nng_stream_listener_accept(arg1: *mut nng_stream_listener, arg2: *mut nng_aio);
}
unsafe extern "C" {
    pub fn nng_stream_listener_get_bool(
        arg1: *mut nng_stream_listener,
        arg2: *const ::core::ffi::c_char,
        arg3: *mut bool,
    ) -> nng_err;
}
unsafe extern "C" {
    pub fn nng_stream_listener_get_int(
        arg1: *mut nng_stream_listener,
        arg2: *const ::core::ffi::c_char,
        arg3: *mut ::core::ffi::c_int,
    ) -> nng_err;
}
unsafe extern "C" {
    pub fn nng_stream_listener_get_ms(
        arg1: *mut nng_stream_listener,
        arg2: *const ::core::ffi::c_char,
        arg3: *mut nng_duration,
    ) -> nng_err;
}
unsafe extern "C" {
    pub fn nng_stream_listener_get_size(
        arg1: *mut nng_stream_listener,
        arg2: *const ::core::ffi::c_char,
        arg3: *mut usize,
    ) -> nng_err;
}
unsafe extern "C" {
    pub fn nng_stream_listener_get_uint64(
        arg1: *mut nng_stream_listener,
        arg2: *const ::core::ffi::c_char,
        arg3: *mut u64,
    ) -> nng_err;
}
unsafe extern "C" {
    pub fn nng_stream_listener_get_string(
        arg1: *mut nng_stream_listener,
        arg2: *const ::core::ffi::c_char,
        arg3: *mut *mut ::core::ffi::c_char,
    ) -> nng_err;
}
unsafe extern "C" {
    pub fn nng_stream_listener_get_addr(
        arg1: *mut nng_stream_listener,
        arg2: *const ::core::ffi::c_char,
        arg3: *mut nng_sockaddr,
    ) -> nng_err;
}
unsafe extern "C" {
    pub fn nng_stream_listener_set_bool(
        arg1: *mut nng_stream_listener,
        arg2: *const ::core::ffi::c_char,
        arg3: bool,
    ) -> nng_err;
}
unsafe extern "C" {
    pub fn nng_stream_listener_set_int(
        arg1: *mut nng_stream_listener,
        arg2: *const ::core::ffi::c_char,
        arg3: ::core::ffi::c_int,
    ) -> nng_err;
}
unsafe extern "C" {
    pub fn nng_stream_listener_set_ms(
        arg1: *mut nng_stream_listener,
        arg2: *const ::core::ffi::c_char,
        arg3: nng_duration,
    ) -> nng_err;
}
unsafe extern "C" {
    pub fn nng_stream_listener_set_size(
        arg1: *mut nng_stream_listener,
        arg2: *const ::core::ffi::c_char,
        arg3: usize,
    ) -> nng_err;
}
unsafe extern "C" {
    pub fn nng_stream_listener_set_uint64(
        arg1: *mut nng_stream_listener,
        arg2: *const ::core::ffi::c_char,
        arg3: u64,
    ) -> nng_err;
}
unsafe extern "C" {
    pub fn nng_stream_listener_set_string(
        arg1: *mut nng_stream_listener,
        arg2: *const ::core::ffi::c_char,
        arg3: *const ::core::ffi::c_char,
    ) -> nng_err;
}
unsafe extern "C" {
    pub fn nng_stream_listener_set_addr(
        arg1: *mut nng_stream_listener,
        arg2: *const ::core::ffi::c_char,
        arg3: *const nng_sockaddr,
    ) -> nng_err;
}
unsafe extern "C" {
    pub fn nng_stream_listener_get_tls(
        arg1: *mut nng_stream_listener,
        arg2: *mut *mut nng_tls_config,
    ) -> nng_err;
}
unsafe extern "C" {
    pub fn nng_stream_listener_set_tls(
        arg1: *mut nng_stream_listener,
        arg2: *mut nng_tls_config,
    ) -> nng_err;
}
unsafe extern "C" {
    pub fn nng_stream_listener_set_security_descriptor(
        arg1: *mut nng_stream_listener,
        arg2: *mut ::core::ffi::c_void,
    ) -> nng_err;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct nng_udp {
    _unused: [u8; 0],
}
unsafe extern "C" {
    pub fn nng_udp_open(udpp: *mut *mut nng_udp, sa: *mut nng_sockaddr) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn nng_udp_stop(udp: *mut nng_udp);
}
unsafe extern "C" {
    pub fn nng_udp_close(udp: *mut nng_udp);
}
unsafe extern "C" {
    pub fn nng_udp_sockname(udp: *mut nng_udp, sa: *mut nng_sockaddr) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn nng_udp_send(udp: *mut nng_udp, aio: *mut nng_aio);
}
unsafe extern "C" {
    pub fn nng_udp_recv(udp: *mut nng_udp, aio: *mut nng_aio);
}
unsafe extern "C" {
    pub fn nng_udp_multicast_membership(
        udp: *mut nng_udp,
        sa: *mut nng_sockaddr,
        join: bool,
    ) -> ::core::ffi::c_int;
}
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct nng_init_params {
    pub num_task_threads: i16,
    pub max_task_threads: i16,
    pub num_expire_threads: i16,
    pub max_expire_threads: i16,
    pub num_poller_threads: i16,
    pub max_poller_threads: i16,
    pub num_resolver_threads: i16,
}
unsafe extern "C" {
    pub fn nng_init(params: *const nng_init_params) -> nng_err;
}
unsafe extern "C" {
    pub fn nng_fini();
}
#[repr(u32)]
#[non_exhaustive]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum nng_log_level {
    NNG_LOG_NONE = 0,
    NNG_LOG_ERR = 3,
    NNG_LOG_WARN = 4,
    NNG_LOG_NOTICE = 5,
    NNG_LOG_INFO = 6,
    NNG_LOG_DEBUG = 7,
}
#[repr(u32)]
#[non_exhaustive]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum nng_log_facility {
    NNG_LOG_USER = 1,
    NNG_LOG_DAEMON = 3,
    NNG_LOG_AUTH = 10,
    NNG_LOG_LOCAL0 = 16,
    NNG_LOG_LOCAL1 = 17,
    NNG_LOG_LOCAL2 = 18,
    NNG_LOG_LOCAL3 = 19,
    NNG_LOG_LOCAL4 = 20,
    NNG_LOG_LOCAL5 = 21,
    NNG_LOG_LOCAL6 = 22,
    NNG_LOG_LOCAL7 = 23,
}
pub type nng_logger = ::core::option::Option<
    unsafe extern "C" fn(
        level: nng_log_level,
        facility: nng_log_facility,
        msgid: *const ::core::ffi::c_char,
        msg: *const ::core::ffi::c_char,
    ),
>;
unsafe extern "C" {
    pub fn nng_null_logger(
        arg1: nng_log_level,
        arg2: nng_log_facility,
        arg3: *const ::core::ffi::c_char,
        arg4: *const ::core::ffi::c_char,
    );
}
unsafe extern "C" {
    pub fn nng_stderr_logger(
        arg1: nng_log_level,
        arg2: nng_log_facility,
        arg3: *const ::core::ffi::c_char,
        arg4: *const ::core::ffi::c_char,
    );
}
unsafe extern "C" {
    pub fn nng_system_logger(
        arg1: nng_log_level,
        arg2: nng_log_facility,
        arg3: *const ::core::ffi::c_char,
        arg4: *const ::core::ffi::c_char,
    );
}
unsafe extern "C" {
    pub fn nng_log_set_facility(facility: nng_log_facility);
}
unsafe extern "C" {
    pub fn nng_log_set_level(level: nng_log_level);
}
unsafe extern "C" {
    pub fn nng_log_get_level() -> nng_log_level;
}
unsafe extern "C" {
    pub fn nng_log_set_logger(logger: nng_logger);
}
unsafe extern "C" {
    pub fn nng_log_err(msgid: *const ::core::ffi::c_char, msg: *const ::core::ffi::c_char, ...);
}
unsafe extern "C" {
    pub fn nng_log_warn(msgid: *const ::core::ffi::c_char, msg: *const ::core::ffi::c_char, ...);
}
unsafe extern "C" {
    pub fn nng_log_notice(msgid: *const ::core::ffi::c_char, msg: *const ::core::ffi::c_char, ...);
}
unsafe extern "C" {
    pub fn nng_log_info(msgid: *const ::core::ffi::c_char, msg: *const ::core::ffi::c_char, ...);
}
unsafe extern "C" {
    pub fn nng_log_debug(msgid: *const ::core::ffi::c_char, msg: *const ::core::ffi::c_char, ...);
}
unsafe extern "C" {
    pub fn nng_log_auth(
        level: nng_log_level,
        msgid: *const ::core::ffi::c_char,
        msg: *const ::core::ffi::c_char,
        ...
    );
}
unsafe extern "C" {
    pub fn nng_clock() -> nng_time;
}
unsafe extern "C" {
    pub fn nng_msleep(arg1: nng_duration);
}
unsafe extern "C" {
    pub fn nng_random() -> u32;
}
unsafe extern "C" {
    pub fn nng_socket_pair(arg1: *mut ::core::ffi::c_int) -> nng_err;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct nng_thread {
    _unused: [u8; 0],
}
unsafe extern "C" {
    pub fn nng_thread_create(
        arg1: *mut *mut nng_thread,
        arg2: ::core::option::Option<unsafe extern "C" fn(arg1: *mut ::core::ffi::c_void)>,
        arg3: *mut ::core::ffi::c_void,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn nng_thread_set_name(arg1: *mut nng_thread, arg2: *const ::core::ffi::c_char);
}
unsafe extern "C" {
    pub fn nng_thread_destroy(arg1: *mut nng_thread);
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct nng_mtx {
    _unused: [u8; 0],
}
unsafe extern "C" {
    pub fn nng_mtx_alloc(arg1: *mut *mut nng_mtx) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn nng_mtx_free(arg1: *mut nng_mtx);
}
unsafe extern "C" {
    pub fn nng_mtx_lock(arg1: *mut nng_mtx);
}
unsafe extern "C" {
    pub fn nng_mtx_unlock(arg1: *mut nng_mtx);
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct nng_cv {
    _unused: [u8; 0],
}
unsafe extern "C" {
    pub fn nng_cv_alloc(arg1: *mut *mut nng_cv, arg2: *mut nng_mtx) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn nng_cv_free(arg1: *mut nng_cv);
}
unsafe extern "C" {
    pub fn nng_cv_wait(arg1: *mut nng_cv);
}
unsafe extern "C" {
    pub fn nng_cv_until(arg1: *mut nng_cv, arg2: nng_time) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn nng_cv_wake(arg1: *mut nng_cv);
}
unsafe extern "C" {
    pub fn nng_cv_wake1(arg1: *mut nng_cv);
}
#[repr(u32)]
#[non_exhaustive]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum nng_tls_mode {
    NNG_TLS_MODE_CLIENT = 0,
    NNG_TLS_MODE_SERVER = 1,
}
#[repr(u32)]
#[non_exhaustive]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum nng_tls_auth_mode {
    NNG_TLS_AUTH_MODE_NONE = 0,
    NNG_TLS_AUTH_MODE_OPTIONAL = 1,
    NNG_TLS_AUTH_MODE_REQUIRED = 2,
}
#[repr(u32)]
#[non_exhaustive]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum nng_tls_version {
    NNG_TLS_1_2 = 771,
    NNG_TLS_1_3 = 772,
}
unsafe extern "C" {
    pub fn nng_tls_config_alloc(
        arg1: *mut *mut nng_tls_config,
        arg2: nng_tls_mode,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn nng_tls_config_hold(arg1: *mut nng_tls_config);
}
unsafe extern "C" {
    pub fn nng_tls_config_free(arg1: *mut nng_tls_config);
}
unsafe extern "C" {
    pub fn nng_tls_config_server_name(
        arg1: *mut nng_tls_config,
        arg2: *const ::core::ffi::c_char,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn nng_tls_config_ca_chain(
        arg1: *mut nng_tls_config,
        arg2: *const ::core::ffi::c_char,
        arg3: *const ::core::ffi::c_char,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn nng_tls_config_own_cert(
        arg1: *mut nng_tls_config,
        arg2: *const ::core::ffi::c_char,
        arg3: *const ::core::ffi::c_char,
        arg4: *const ::core::ffi::c_char,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn nng_tls_config_key(
        arg1: *mut nng_tls_config,
        arg2: *const u8,
        arg3: usize,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn nng_tls_config_pass(
        arg1: *mut nng_tls_config,
        arg2: *const ::core::ffi::c_char,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn nng_tls_config_auth_mode(
        arg1: *mut nng_tls_config,
        arg2: nng_tls_auth_mode,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn nng_tls_config_ca_file(
        arg1: *mut nng_tls_config,
        arg2: *const ::core::ffi::c_char,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn nng_tls_config_cert_key_file(
        arg1: *mut nng_tls_config,
        arg2: *const ::core::ffi::c_char,
        arg3: *const ::core::ffi::c_char,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn nng_tls_config_psk(
        arg1: *mut nng_tls_config,
        arg2: *const ::core::ffi::c_char,
        arg3: *const u8,
        arg4: usize,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn nng_tls_config_version(
        arg1: *mut nng_tls_config,
        arg2: nng_tls_version,
        arg3: nng_tls_version,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn nng_tls_engine_name() -> *const ::core::ffi::c_char;
}
unsafe extern "C" {
    pub fn nng_tls_engine_description() -> *const ::core::ffi::c_char;
}
unsafe extern "C" {
    pub fn nng_tls_engine_fips_mode() -> bool;
}
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct nng_id_map_s {
    _unused: [u8; 0],
}
pub type nng_id_map = nng_id_map_s;
unsafe extern "C" {
    pub fn nng_id_map_alloc(
        map: *mut *mut nng_id_map,
        lo: u64,
        hi: u64,
        flags: ::core::ffi::c_int,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn nng_id_map_free(map: *mut nng_id_map);
}
unsafe extern "C" {
    pub fn nng_id_get(arg1: *mut nng_id_map, arg2: u64) -> *mut ::core::ffi::c_void;
}
unsafe extern "C" {
    pub fn nng_id_set(
        arg1: *mut nng_id_map,
        arg2: u64,
        arg3: *mut ::core::ffi::c_void,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn nng_id_alloc(
        arg1: *mut nng_id_map,
        arg2: *mut u64,
        arg3: *mut ::core::ffi::c_void,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn nng_id_remove(arg1: *mut nng_id_map, arg2: u64) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn nng_id_visit(
        arg1: *mut nng_id_map,
        arg2: *mut u64,
        arg3: *mut *mut ::core::ffi::c_void,
        arg4: *mut u32,
    ) -> bool;
}
unsafe extern "C" {
    pub fn nng_bus0_open(arg1: *mut nng_socket) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn nng_bus0_open_raw(arg1: *mut nng_socket) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn nng_pair0_open(arg1: *mut nng_socket) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn nng_pair0_open_raw(arg1: *mut nng_socket) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn nng_pair1_open(arg1: *mut nng_socket) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn nng_pair1_open_raw(arg1: *mut nng_socket) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn nng_pair1_open_poly(arg1: *mut nng_socket) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn nng_pull0_open(arg1: *mut nng_socket) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn nng_pull0_open_raw(arg1: *mut nng_socket) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn nng_push0_open(arg1: *mut nng_socket) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn nng_push0_open_raw(arg1: *mut nng_socket) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn nng_pub0_open(arg1: *mut nng_socket) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn nng_pub0_open_raw(arg1: *mut nng_socket) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn nng_sub0_open(arg1: *mut nng_socket) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn nng_sub0_open_raw(arg1: *mut nng_socket) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn nng_sub0_socket_subscribe(
        id: nng_socket,
        buf: *const ::core::ffi::c_void,
        sz: usize,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn nng_sub0_socket_unsubscribe(
        id: nng_socket,
        buf: *const ::core::ffi::c_void,
        sz: usize,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn nng_sub0_ctx_subscribe(
        id: nng_ctx,
        buf: *const ::core::ffi::c_void,
        sz: usize,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn nng_sub0_ctx_unsubscribe(
        id: nng_ctx,
        buf: *const ::core::ffi::c_void,
        sz: usize,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn nng_rep0_open(arg1: *mut nng_socket) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn nng_rep0_open_raw(arg1: *mut nng_socket) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn nng_req0_open(arg1: *mut nng_socket) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn nng_req0_open_raw(arg1: *mut nng_socket) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn nng_respondent0_open(arg1: *mut nng_socket) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn nng_respondent0_open_raw(arg1: *mut nng_socket) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn nng_surveyor0_open(arg1: *mut nng_socket) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn nng_surveyor0_open_raw(arg1: *mut nng_socket) -> ::core::ffi::c_int;
}
#[repr(u32)]
#[non_exhaustive]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum nng_http_status {
    NNG_HTTP_STATUS_CONTINUE = 100,
    NNG_HTTP_STATUS_SWITCHING = 101,
    NNG_HTTP_STATUS_PROCESSING = 102,
    NNG_HTTP_STATUS_OK = 200,
    NNG_HTTP_STATUS_CREATED = 201,
    NNG_HTTP_STATUS_ACCEPTED = 202,
    NNG_HTTP_STATUS_NOT_AUTHORITATIVE = 203,
    NNG_HTTP_STATUS_NO_CONTENT = 204,
    NNG_HTTP_STATUS_RESET_CONTENT = 205,
    NNG_HTTP_STATUS_PARTIAL_CONTENT = 206,
    NNG_HTTP_STATUS_MULTI_STATUS = 207,
    NNG_HTTP_STATUS_ALREADY_REPORTED = 208,
    NNG_HTTP_STATUS_IM_USED = 226,
    NNG_HTTP_STATUS_MULTIPLE_CHOICES = 300,
    NNG_HTTP_STATUS_STATUS_MOVED_PERMANENTLY = 301,
    NNG_HTTP_STATUS_FOUND = 302,
    NNG_HTTP_STATUS_SEE_OTHER = 303,
    NNG_HTTP_STATUS_NOT_MODIFIED = 304,
    NNG_HTTP_STATUS_USE_PROXY = 305,
    NNG_HTTP_STATUS_TEMPORARY_REDIRECT = 307,
    NNG_HTTP_STATUS_PERMANENT_REDIRECT = 308,
    NNG_HTTP_STATUS_BAD_REQUEST = 400,
    NNG_HTTP_STATUS_UNAUTHORIZED = 401,
    NNG_HTTP_STATUS_PAYMENT_REQUIRED = 402,
    NNG_HTTP_STATUS_FORBIDDEN = 403,
    NNG_HTTP_STATUS_NOT_FOUND = 404,
    NNG_HTTP_STATUS_METHOD_NOT_ALLOWED = 405,
    NNG_HTTP_STATUS_NOT_ACCEPTABLE = 406,
    NNG_HTTP_STATUS_PROXY_AUTH_REQUIRED = 407,
    NNG_HTTP_STATUS_REQUEST_TIMEOUT = 408,
    NNG_HTTP_STATUS_CONFLICT = 409,
    NNG_HTTP_STATUS_GONE = 410,
    NNG_HTTP_STATUS_LENGTH_REQUIRED = 411,
    NNG_HTTP_STATUS_PRECONDITION_FAILED = 412,
    NNG_HTTP_STATUS_CONTENT_TOO_LARGE = 413,
    NNG_HTTP_STATUS_URI_TOO_LONG = 414,
    NNG_HTTP_STATUS_UNSUPPORTED_MEDIA_TYPE = 415,
    NNG_HTTP_STATUS_RANGE_NOT_SATISFIABLE = 416,
    NNG_HTTP_STATUS_EXPECTATION_FAILED = 417,
    NNG_HTTP_STATUS_TEAPOT = 418,
    NNG_HTTP_STATUS_UNPROCESSABLE_ENTITY = 422,
    NNG_HTTP_STATUS_LOCKED = 423,
    NNG_HTTP_STATUS_FAILED_DEPENDENCY = 424,
    NNG_HTTP_STATUS_TOO_EARLY = 425,
    NNG_HTTP_STATUS_UPGRADE_REQUIRED = 426,
    NNG_HTTP_STATUS_PRECONDITION_REQUIRED = 428,
    NNG_HTTP_STATUS_TOO_MANY_REQUESTS = 429,
    NNG_HTTP_STATUS_HEADERS_TOO_LARGE = 431,
    NNG_HTTP_STATUS_UNAVAIL_LEGAL_REASONS = 451,
    NNG_HTTP_STATUS_INTERNAL_SERVER_ERROR = 500,
    NNG_HTTP_STATUS_NOT_IMPLEMENTED = 501,
    NNG_HTTP_STATUS_BAD_GATEWAY = 502,
    NNG_HTTP_STATUS_SERVICE_UNAVAILABLE = 503,
    NNG_HTTP_STATUS_GATEWAY_TIMEOUT = 504,
    NNG_HTTP_STATUS_HTTP_VERSION_NOT_SUPP = 505,
    NNG_HTTP_STATUS_VARIANT_ALSO_NEGOTIATES = 506,
    NNG_HTTP_STATUS_INSUFFICIENT_STORAGE = 507,
    NNG_HTTP_STATUS_LOOP_DETECTED = 508,
    NNG_HTTP_STATUS_NOT_EXTENDED = 510,
    NNG_HTTP_STATUS_NETWORK_AUTH_REQUIRED = 511,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct nng_http_req {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct nng_http_res {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct nng_http_conn {
    _unused: [u8; 0],
}
pub type nng_http = nng_http_conn;
unsafe extern "C" {
    pub fn nng_http_close(arg1: *mut nng_http);
}
unsafe extern "C" {
    pub fn nng_http_read(arg1: *mut nng_http, arg2: *mut nng_aio);
}
unsafe extern "C" {
    pub fn nng_http_read_all(arg1: *mut nng_http, arg2: *mut nng_aio);
}
unsafe extern "C" {
    pub fn nng_http_write(arg1: *mut nng_http, arg2: *mut nng_aio);
}
unsafe extern "C" {
    pub fn nng_http_write_all(arg1: *mut nng_http, arg2: *mut nng_aio);
}
unsafe extern "C" {
    pub fn nng_http_write_request(arg1: *mut nng_http, arg2: *mut nng_aio);
}
unsafe extern "C" {
    pub fn nng_http_write_response(arg1: *mut nng_http, arg2: *mut nng_aio);
}
unsafe extern "C" {
    pub fn nng_http_read_response(arg1: *mut nng_http, arg2: *mut nng_aio);
}
unsafe extern "C" {
    pub fn nng_http_reset(arg1: *mut nng_http);
}
unsafe extern "C" {
    pub fn nng_http_set_uri(
        arg1: *mut nng_http,
        arg2: *const ::core::ffi::c_char,
        arg3: *const ::core::ffi::c_char,
    ) -> nng_err;
}
unsafe extern "C" {
    pub fn nng_http_get_uri(arg1: *mut nng_http) -> *const ::core::ffi::c_char;
}
unsafe extern "C" {
    pub fn nng_http_get_status(arg1: *mut nng_http) -> nng_http_status;
}
unsafe extern "C" {
    pub fn nng_http_get_reason(arg1: *mut nng_http) -> *const ::core::ffi::c_char;
}
unsafe extern "C" {
    pub fn nng_http_set_status(
        arg1: *mut nng_http,
        arg2: nng_http_status,
        arg3: *const ::core::ffi::c_char,
    );
}
unsafe extern "C" {
    pub fn nng_http_set_version(arg1: *mut nng_http, arg2: *const ::core::ffi::c_char) -> nng_err;
}
unsafe extern "C" {
    pub fn nng_http_get_version(arg1: *mut nng_http) -> *const ::core::ffi::c_char;
}
unsafe extern "C" {
    pub fn nng_http_set_method(arg1: *mut nng_http, arg2: *const ::core::ffi::c_char);
}
unsafe extern "C" {
    pub fn nng_http_get_method(arg1: *mut nng_http) -> *const ::core::ffi::c_char;
}
unsafe extern "C" {
    pub fn nng_http_set_header(
        arg1: *mut nng_http,
        arg2: *const ::core::ffi::c_char,
        arg3: *const ::core::ffi::c_char,
    ) -> nng_err;
}
unsafe extern "C" {
    pub fn nng_http_add_header(
        arg1: *mut nng_http,
        arg2: *const ::core::ffi::c_char,
        arg3: *const ::core::ffi::c_char,
    ) -> nng_err;
}
unsafe extern "C" {
    pub fn nng_http_del_header(arg1: *mut nng_http, arg2: *const ::core::ffi::c_char);
}
unsafe extern "C" {
    pub fn nng_http_get_header(
        arg1: *mut nng_http,
        arg2: *const ::core::ffi::c_char,
    ) -> *const ::core::ffi::c_char;
}
unsafe extern "C" {
    pub fn nng_http_get_body(
        arg1: *mut nng_http,
        arg2: *mut *mut ::core::ffi::c_void,
        arg3: *mut usize,
    );
}
unsafe extern "C" {
    pub fn nng_http_set_body(arg1: *mut nng_http, arg2: *mut ::core::ffi::c_void, arg3: usize);
}
unsafe extern "C" {
    pub fn nng_http_copy_body(
        arg1: *mut nng_http,
        arg2: *const ::core::ffi::c_void,
        arg3: usize,
    ) -> nng_err;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct nng_http_handler {
    _unused: [u8; 0],
}
pub type nng_http_handler_func = ::core::option::Option<
    unsafe extern "C" fn(arg1: *mut nng_http, arg2: *mut ::core::ffi::c_void, arg3: *mut nng_aio),
>;
unsafe extern "C" {
    pub fn nng_http_handler_alloc(
        arg1: *mut *mut nng_http_handler,
        arg2: *const ::core::ffi::c_char,
        arg3: nng_http_handler_func,
    ) -> nng_err;
}
unsafe extern "C" {
    pub fn nng_http_handler_free(arg1: *mut nng_http_handler);
}
unsafe extern "C" {
    pub fn nng_http_handler_alloc_file(
        arg1: *mut *mut nng_http_handler,
        arg2: *const ::core::ffi::c_char,
        arg3: *const ::core::ffi::c_char,
    ) -> nng_err;
}
unsafe extern "C" {
    pub fn nng_http_handler_alloc_static(
        arg1: *mut *mut nng_http_handler,
        arg2: *const ::core::ffi::c_char,
        arg3: *const ::core::ffi::c_void,
        arg4: usize,
        arg5: *const ::core::ffi::c_char,
    ) -> nng_err;
}
unsafe extern "C" {
    pub fn nng_http_handler_alloc_redirect(
        arg1: *mut *mut nng_http_handler,
        arg2: *const ::core::ffi::c_char,
        arg3: nng_http_status,
        arg4: *const ::core::ffi::c_char,
    ) -> nng_err;
}
unsafe extern "C" {
    pub fn nng_http_handler_alloc_directory(
        arg1: *mut *mut nng_http_handler,
        arg2: *const ::core::ffi::c_char,
        arg3: *const ::core::ffi::c_char,
    ) -> nng_err;
}
unsafe extern "C" {
    pub fn nng_http_handler_set_method(
        arg1: *mut nng_http_handler,
        arg2: *const ::core::ffi::c_char,
    );
}
unsafe extern "C" {
    pub fn nng_http_handler_set_host(arg1: *mut nng_http_handler, arg2: *const ::core::ffi::c_char);
}
unsafe extern "C" {
    pub fn nng_http_handler_collect_body(arg1: *mut nng_http_handler, arg2: bool, arg3: usize);
}
unsafe extern "C" {
    pub fn nng_http_handler_set_tree(arg1: *mut nng_http_handler);
}
unsafe extern "C" {
    pub fn nng_http_handler_set_data(
        arg1: *mut nng_http_handler,
        arg2: *mut ::core::ffi::c_void,
        arg3: ::core::option::Option<unsafe extern "C" fn(arg1: *mut ::core::ffi::c_void)>,
    );
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct nng_http_server {
    _unused: [u8; 0],
}
unsafe extern "C" {
    pub fn nng_http_server_hold(arg1: *mut *mut nng_http_server, arg2: *const nng_url) -> nng_err;
}
unsafe extern "C" {
    pub fn nng_http_server_release(arg1: *mut nng_http_server);
}
unsafe extern "C" {
    pub fn nng_http_server_start(arg1: *mut nng_http_server) -> nng_err;
}
unsafe extern "C" {
    pub fn nng_http_server_stop(arg1: *mut nng_http_server);
}
unsafe extern "C" {
    pub fn nng_http_server_add_handler(
        arg1: *mut nng_http_server,
        arg2: *mut nng_http_handler,
    ) -> nng_err;
}
unsafe extern "C" {
    pub fn nng_http_server_del_handler(
        arg1: *mut nng_http_server,
        arg2: *mut nng_http_handler,
    ) -> nng_err;
}
unsafe extern "C" {
    pub fn nng_http_server_set_tls(
        arg1: *mut nng_http_server,
        arg2: *mut nng_tls_config,
    ) -> nng_err;
}
unsafe extern "C" {
    pub fn nng_http_server_get_tls(
        arg1: *mut nng_http_server,
        arg2: *mut *mut nng_tls_config,
    ) -> nng_err;
}
unsafe extern "C" {
    pub fn nng_http_server_get_addr(arg1: *mut nng_http_server, arg2: *mut nng_sockaddr)
    -> nng_err;
}
unsafe extern "C" {
    pub fn nng_http_server_set_error_page(
        arg1: *mut nng_http_server,
        arg2: nng_http_status,
        arg3: *const ::core::ffi::c_char,
    ) -> nng_err;
}
unsafe extern "C" {
    pub fn nng_http_server_set_error_file(
        arg1: *mut nng_http_server,
        arg2: nng_http_status,
        arg3: *const ::core::ffi::c_char,
    ) -> nng_err;
}
unsafe extern "C" {
    pub fn nng_http_server_error(arg1: *mut nng_http_server, arg2: *mut nng_http) -> nng_err;
}
unsafe extern "C" {
    pub fn nng_http_hijack(arg1: *mut nng_http) -> nng_err;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct nng_http_client {
    _unused: [u8; 0],
}
unsafe extern "C" {
    pub fn nng_http_client_alloc(arg1: *mut *mut nng_http_client, arg2: *const nng_url) -> nng_err;
}
unsafe extern "C" {
    pub fn nng_http_client_free(arg1: *mut nng_http_client);
}
unsafe extern "C" {
    pub fn nng_http_client_set_tls(
        arg1: *mut nng_http_client,
        arg2: *mut nng_tls_config,
    ) -> nng_err;
}
unsafe extern "C" {
    pub fn nng_http_client_get_tls(
        arg1: *mut nng_http_client,
        arg2: *mut *mut nng_tls_config,
    ) -> nng_err;
}
unsafe extern "C" {
    pub fn nng_http_client_connect(arg1: *mut nng_http_client, arg2: *mut nng_aio);
}
unsafe extern "C" {
    pub fn nng_http_transact(arg1: *mut nng_http, arg2: *mut nng_aio);
}
